apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mattermost-pvc
  namespace: ${NAMESPACE_MATTERMOST}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mattermost
  namespace: ${NAMESPACE_MATTERMOST}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mattermost
  template:
    metadata:
      labels:
        app: mattermost
    spec:
      containers:
      - name: mattermost
        image: mattermost/mattermost-team-edition:latest
        ports:
        - containerPort: 8065
        env:
        - name: MM_SQLSETTINGS_DRIVERNAME
          value: postgres
        - name: MM_SQLSETTINGS_DATASOURCE
          value: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=disable"
        - name: MM_SERVICESETTINGS_SITEURL
          value: "${MATTERMOST_SITE_URL}"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "400m"
        volumeMounts:
        - name: mattermost-storage
          mountPath: /mattermost/data
      volumes:
      - name: mattermost-storage
        persistentVolumeClaim:
          claimName: mattermost-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: mattermost
  namespace: ${NAMESPACE_MATTERMOST}
spec:
  type: NodePort
  selector:
    app: mattermost
  ports:
  - port: 8065
    targetPort: 8065
    nodePort: 30000
